// Generated by https://quicktype.io

import { AxiosResponse } from 'axios';

export interface CartResponse {
  isSuccessful: boolean;
  message: null;
  data: Data;
  errors: any[];
}

export interface Data {
  id: null;
  user: User;
  status: string;
  shoppingCartAbandoned: boolean;
  updateCartBitacoraBD: boolean;
  cartUniqueId: string;
  createdAt: string;
  updatedAt: string;
  cartAttributes: CartAttributes;
}

export interface CartAttributes {
  notes: null;
  total: string;
  totalItems: number;
  products: Product[];
}

export interface Product {
  id: string;
  quantity: number;
  productTotal: number;
  quantityAvailable: string;
  iva: number;
  stockDecreaseUpdate: boolean;
  attributes: Attributes;
}

export interface Attributes {
  sku: string;
  images: string[];
  stock: number;
  value: number;
  quantityByCart: number;
  name: string;
  type: string;
  sellerId: number;
  assumedValue: number;
  regularPrice: number;
  length: number;
  width: number;
  height: number;
  weight: number;
  warehouseId: number;
  checkTransport: boolean;
  categories: any[];
}

export interface User {
  userUniqueId: string;
  email: string;
  userName: string;
  phone: string;
  address: string;
}
export interface ICartProduct {
  cart: Cart;
  product: CartProduct;
}

export interface Cart {
  cartUniqueId: string;
  user_info: UserInfo;
  notes: string;
}

export interface UserInfo {
  uniqueId: string;
  email: string;
  userName: string;
  phone: string;
  address: string;
}

export interface CartProduct {
  productId?: string;
  quantity: number;
}

export interface CartProductAxiosresponse {
  isSuccessful: boolean;
  message: null;
  data: IData;
  errors: any[];
}

export interface IData {
  id: null;
  user: IUser;
  status: string;
  shoppingCartAbandoned: boolean;
  updateCartBitacoraBD: boolean;
  cartUniqueId: string;
  createdAt: string;
  updatedAt: string;
  cartAttributes: ICartAttributes;
}

export interface ICartAttributes {
  notes: null;
  total: string;
  totalItems: number;
  products: IAxiosProduct[];
}

export interface IAxiosProduct {
  id: string;
  quantity: number;
  productTotal: number;
  quantityAvailable: string;
  iva: number;
  stockDecreaseUpdate: boolean;
  attributes: Attributes;
}

export interface IAttributes {
  sku: string;
  images: string[];
  stock: number;
  value: number;
  quantityByCart: number;
  name: string;
  type: string;
  sellerId: number;
  assumedValue: number;
  regularPrice: number;
  length: number;
  width: number;
  height: number;
  weight: number;
  warehouseId: number;
  checkTransport: boolean;
  categories: any[];
}

export interface IUser {
  userUniqueId: string;
  email: string;
  userName: string;
  phone: string;
  address: string;
}

export interface IUseCart {
  data: AxiosResponse<any, any> | undefined;
  addProductToCart: (
    newProduct: any,
    action?: string
  ) => Promise<AxiosResponse<any, any> | undefined>;
  error: any;
  loading: boolean;
}
